server {
    listen 4321;
    listen [::]:4321;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # compressione
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    # asset con hash di Astro: cache lunga e immutabile
    location /_astro/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # media: cache media
    location ~* \.(jpg|jpeg|png|webp|gif|svg|mp3|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    # URL puliti + fallback
    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
